### ISSUE TITLE
Usage needs to be updated to include required provider aliases

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-secrets-manager-public-cert-engine#75]
https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-public-cert-engine?tab=readme-ov-file#usage

^ The usage needs to be updated to include the required providers block since the module requires it:
```
providers = {
    ibm              = ibm
    ibm.secret-store = ibm
  }
```

We should probably mention why its required to avoid any confusion. From codeowner:

> A quick look suggests that the module can be used in one of two ways. Either a key (acme_letsencrypt_private_key) can be passed or a secret (in secrets manager) can be passed by id/guid.
> The secret can be in a different secrets manager, in a different account in a different region. This is supported by passing a second provider (it can have the same, or a different api key).
> There need to be two providers so that the engine can be configured in one instance, whilst the acme key can be looked up in another.

**Comment by kierramarie** [comment]
Pr merged. Closing issue.
